### ISSUE TITLE
[LuaLaTex] Hyphenation ignored when in brackets and italics

### ISSUE THREAD

**Issue by apepper** [latex3/fontspec#112]
# Minimal example

``` latex
\documentclass[twocolumn]{book}
%\usepackage{fontspec}

\begin{document}
Hello World. Thisshouldbesometext with a bug-report.

Hello World. Thisshouldbesometext with a \emph{bug-report}.

Hello World. Thisshouldbesometext with a (\emph{bug-report}).

Hello World. Thisshouldbesometext with a (bug-report).

Hello World. Thisshouldbesometext with a \emph{(bug-report)}.
\end{document}
```
# The problem

As soon as fontspec is loaded words, which are in brackets and italics (e.g. `(\emph{bug-report})` are not hyphenated at the minus. If the brackets are inside the italics all is fine. Also everything is working, when no italics or brackets are given.
# The version

Latest LiveTex 2011 on OSX 10.6.8 with lualatex and fontspec:
    This is LuaTeX, Version beta-0.70.1-2011062107 (rev 4277)
    fontspec 2011/09/18 v2.2a (TeX Live Util claims build 24004)

I'm not really sure, if this is a fontspec or a LuaLaTeX bug, but without fontspec, LuaLaTeX is able to correctly hyphenated.

**Comment by u-fischer** [comment]
In texlive 2022 everything looks correct, so closing.
