### ISSUE TITLE
missing begin document error with Renderer=Harfbuzz/OpenType

### ISSUE THREAD

**Issue by u-fischer** [latex3/fontspec#370]
## Description
`Renderer=Harfbuzz` and `Renderer=OpenType` give errors

## Check/indicate
- [ x] Relevant for LuaTeX /Harftex
- [x ] Issue tracker has been searched for similar issues?
- [x] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{harfload}
\usepackage{fontspec}

\setmainfont{texgyreheros}[Renderer=OpenType] %or Renderer=Harfbuzz

\begin{document}
blub
\end{document}
```

## Further details

this gives the error (when compiling with harflatex, but also with lualatex)

~~~~
LaTeX Info: Redefining \emph on input line 3853.
))

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.332 \setmainfont{texgyreheros}[Renderer=OpenType]
~~~~

**Comment by wspr** [comment]
Errrr whoops

**Comment by u-fischer** [comment]
This is no longer relevant as the harfload approach has been superseeded by luahbtex.
