### ISSUE TITLE
Italic not correctly selected for Libertinus Serif

### ISSUE THREAD

**Issue by wujastyk** [latex3/fontspec#377]
## Description
The Libertinus Serif and Sans fonts produce bold italic when ordinary italic is invoked. This behaviour only started with the update to TeXlive 2019.  With TL2018, there was no problem.

## Check/indicate
- [ X] Relevant for XeTeX
- [ ] Relevant for LuaTeX
- [X ] Issue tracker has been searched for similar issues?
Is this the same as issue #233?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

Output of MWE below:

![helloworld](https://user-images.githubusercontent.com/762246/62420641-fbd31900-b652-11e9-9931-06509898fc0a.png)

## Minimal example demonstrating the issue
```
% !TEX program = xelatex
% !TEX encoding = UTF-8
\documentclass{minimal}
\usepackage{fontspec}
\begin{document}
\setmainfont{Libertinus Serif}
Hello world! \emph{Hello world!}

\setmainfont{Linux Libertine O}
Hello world! \emph{Hello world!}
\end{document}


## Further details

**Comment by wujastyk** [comment]
Is the answer to have a file LibertinusSerif.fontspec with the following content?

```
\defaultfontfeatures[Libertinus Serif]
  {
  Extension = .otf ,
  UprightFont = LibertinusSerif-Regular,
  BoldFont = LibertinusSerif-Bold,
  ItalicFont = LibertinusSerif-Italic,
  BoldItalicFont = LibertinusSerif-BoldItalic
  }
```

and similar for Sans?

**Comment by u-fischer** [comment]
Closing as it looks fine in a current texlive 2022.
