### ISSUE TITLE
Upload announcements broken with \

### ISSUE THREAD

**Issue by wspr** [latex3/fontspec#399]
## Description

From Petra regarding my last upload:

```
 Seems to have worked fine, in principle, except for `\verbvisiblespace`,
 which was rendered as `^Kerbvisiblespace` in the upload notification
 email for maintainers  and as  `
                                 erbvisiblespace`
 in a metadata file on the server.

```

**Comment by davidcarlisle** [comment]
I think l3build upload should double up \ if reading from a file  (or perhaps always?) 
If just doing it for files then:


```
  -- Get data from command line if appropriate
  if options["file"] then
    local f = open(options["file"],"r")
    uploadconfig.announcement = assert(f:read('*a'))
    uploadconfig.announcement=string.gsub(uploadconfig.announcement,'\\','\\\\') -- this line added
    close(f)
  end
```

Curl manual says

> 
> If the parameter contains whitespace (or starts with : or =), the parameter must be enclosed within quotes.  Within
> double  quotes,  the following escape sequences are available: `\\, \", \t, \n, \r and \v`. A backslash preceding any
> other letter is ignored. If the first column of a config line is a '#' character, the rest  of  the  line  will  be
> treated as a comment. Only write one option per physical line in the config file.
> 
>

**Comment by wspr** [comment]
I don't think there have been issues about this with recent releases; assume fixed
