### ISSUE TITLE
Broken examples in v2.7e documentation

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/fontspec#400]
## Description
In `2020/01/09 v2.7e`, several examples in the documentation are broken:
- Example 35: Numbers can be compressed significantly.
- Example 38: Contextual glyph for the beginnings and ends of words.
- Example 39: A contextual feature for the ‘long s’ […]
- Example 40: Vertical position for AAT fonts.
- Example 43: Nine variants of Zapfino.
- Example 44: Alternate shape selection must be numerical.
- Example 46: Assigning new AAT features.

There is one more problem for Example 44: The `Alternate` feature is not applied, neither is `\scshape`, when compared to `2018/07/30 v2.6h`.

Lastly, the last glyph in *Example 45: Vertical typesetting* is clipped. Perhaps a negative vspace will help.

**Comment by wspr** [comment]
Thanks for spotting this. The XeTeX on the latest version of macOS seems to have problems with the AAT fonts that are shipped with the OS. I'm not sure if this is a XeTeX problem, a macOS problem, or a font problem... regardless I think it might be time to start retiring the AAT code...

**Comment by wspr** [comment]
I have stripped out all of the AAT examples now, so I think this should be (indirectly) addressed.
