### ISSUE TITLE
Small caps broken in LuaLaTeX-dev when using Renderer=Harfbuzz

### ISSUE THREAD

**Issue by bgvoisin** [latex3/fontspec#402]
## Description
Small caps in LuaLaTeX-dev are OK when using RawFeature={mode=harf} but broken when using Renderer=Harfbuzz

## Check/indicate
- [ ] Relevant for XeTeX
- [*] Relevant for LuaTeX
- [*] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{fontspec}
\setlength{\parindent}{0pt}
\setlength{\parskip}{\normalbaselineskip}
\begin{document}
Standard text. \textsc{Small caps text}.
\par
\fontspec{texgyretermes-regular.otf}%
Switch to TeX Gyre Termes \\
Standard text. \textsc{Small caps text}.
\par
\fontspec{texgyretermes-regular.otf}[Renderer=Harfbuzz]%
Switch to TeX Gyre Termes with \verb+Renderer=Harfbuzz+ \\
Standard text. \textsc{Small caps text}.
\par
\fontspec{texgyretermes-regular.otf}[RawFeature={mode=harf}]%
Switch to TeX Gyre Termes with \verb+RawFeature={mode=harf}+ \\
Standard text. \textsc{Small caps text}.
\end{document}
```

## Further details
Might be linked to https://github.com/wspr/fontspec/issues/396. I'm not quite sure how to test for that. The bug was noticed today with everything updated via tlmgr (actually TeX Live Utility on the Mac, with MacTeX 2019 installed). Fontspec v2.7e from 2020/01/09.

[SmallCapsTest.pdf](https://github.com/wspr/fontspec/files/4058768/SmallCapsTest.pdf)

**Comment by u-fischer** [comment]
It works for me when I use the development version of luaotfload.

**Comment by bgvoisin** [comment]
> Le 18 janv. 2020 à 23:03, Ulrike Fischer <notifications@github.com> a écrit :
> 
> It works for me when I use the development version of luaotfload.

I can confirm this (with the dev branch downloaded from https://github.com/latex3/luaotfload this morning and installed manually — I couldn’t find the texmf folder mentioned in luaotfload-dev/doc/CTANREADME.md).

Bruno

**Comment by u-fischer** [comment]
@bgvoisin  I adapted the readme (only in the dev branch for now), I hope this is clearer. I will try to release a new luaotfload version soon to resolve this problem.

**Comment by bgvoisin** [comment]
@u-fischer Thanks for pointing to l3build in the readme. That seems very convenient, I didn't know about it. It took a bit of time to figure out how to clone (I had never used git on the command line before): selecting the dev branch and the "Clone or download" button in the web interface doesn't work, because the .git directory isn't included in the download and l3build seems to require it. But running instead
`git clone --single-branch --branch dev https://github.com/latex3/luaotfload`
gets a clone that l3build can use. One remark: after running l3build, the luaotfload-tool symlink in SELFAUTOLOC still points to luaotfload-tool.lua in TEXMFDIST, not the newly installed luaotfload-tool.lua in TEXMFHOME. Is this how it's supposed to be?

**Comment by u-fischer** [comment]
Yes as far as I know texlive doesn't run scripts from local texmf trees. But normally this shouldn't matter much, the scripts files don't change so much

**Comment by u-fischer** [comment]
closing as resolved by luaotfload update.
