### ISSUE TITLE
BoldFeatures within \defaultfontfeatures

### ISSUE THREAD

**Issue by Davislor** [latex3/fontspec#436]
## Description
Using `BoldFeatures =` inside `\defaultfontfeatures` gives an error.

## Check/indicate
- [x] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{fontspec}

\defaultfontfeatures[FreeSerif]{
  BoldFont=*,
  BoldFeatures = {FakeBold = 1.2} }

\setmainfont{FreeSerif}

\begin{document}
\maketitle
\end{document}
```

## Further details

On an up-to-date TeX Live 2020, this gives the error
```
! LaTeX3 Error: The key 'fontspec-opentype/BoldFeatures' is unknown and is
(LaTeX3)        being ignored.
```

**Comment by chrullrich** [comment]
I was able to get around that by changing `fontspec-preparse` to `fontspec-opentype` between lines 2308 and 2366 of `fontspec-luatex.sty` and lines 2416 and 2444 of `fontspec-xetex.sty` (built from current git). A very simple test document that exercises UprightFeatures, BoldFeatures, etc. combined with SizeFeatures for the optical sizes of Source Serif 4 as well as a 180-page doc that uses only a few different faces compiled with both lualatex and xelatex and looked OK to me.

No idea what may break from this change that I just have not seen yet. My guess (and it really is one) is that anything other than my exact circumstances (installed OpenType fonts on Windows) will not work anymore.

**Comment by chrullrich** [comment]
This works perfectly with my two test documents, with both LuaTeX and XeTeX from MiKTeX and installed OpenType fonts. Guessing further, I would expect it to work in any OpenType situation. Would the same change be required for the Graphite/AAT case with XeTeX? I don't have a Mac handy to try.

**Comment by wspr** [comment]
This has now been resolved
