### ISSUE TITLE
Weird annoying fontspec BUG

### ISSUE THREAD

**Issue by vafa-khalighi** [latex3/fontspec#456]
## Description
If you use Graphite Renderer and arabic script, then fontspec complain that the selcted font does not contain arabic script and the text is not rendered correctly.

For the purpose of this bug report, you can test using [AWAMI NASTALIQ font](https://software.sil.org/awami/).

This issue does not happen in Plain TeX or when using `\font` control sequence directly in LaTeX. See my second minimal example.

The `Script=Arabic` is needed since XeTeX does some unicode bidi; without this, parentheses, etc will be wrong.

## Check/indicate
- [x] Relevant for XeTeX
- [ ] Relevant for LuaTeX
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{AwamiNastaliq-Regular}[Path,Renderer=Graphite,Script=Arabic]
\begin{document}
وفا
\end{document}
```
and here is the plain tex one.

```tex
\font\test="[AwamiNastaliq-Regular]/GR:script=arab" at 20pt
\test
وفا
\bye
```

**Comment by u-fischer** [comment]
Well the documentation of fontspec writes

> Currently fontspec does not support a convenient interface to select Graphite font features
and all selection must be done via ‘raw’ font feature selection.

so use

      \setmainfont{AwamiNastaliq-Regular}[Path,Renderer=Graphite,RawFeature={script=arab;}]

**Comment by niruvt** [comment]
@wspr Please have a look at [this](https://tex.stackexchange.com/a/713681).

**Comment by wspr** [comment]
@niruvt  — thanks for making the connection

**Comment by niruvt** [comment]
@wspr Thanks a lot for the fix!
