### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by adwq13** [latex3/fontspec#457]
\documentclass{article}

\usepackage{polyglossia}

\newfontfamily{\arebicfont}[sript=Arabic]{Amiri}

\begin{document}
	
	ergewge
	
	
	
	
\end{document}

**Comment by adwq13** [comment]
![لقطة الشاشة 2022-03-17 110810](https://user-images.githubusercontent.com/101794033/158764673-f1bb1736-db48-4e70-93b6-00da027a0d4f.png)

**Comment by u-fischer** [comment]
closing as the wrong engine was used.
