### ISSUE TITLE
fontspec can't find font with curly quotes in embedded description

### ISSUE THREAD

**Issue by ksch1186** [latex3/fontspec#458]
## Description
I'm trying to use fonts Petrona*ttf, which fails with a message font can't be found.

\setmainfont{Petrona}[
	UprightFont = *-Regular,
	ItalicFont = *-Italic,
	BoldFont = *-Bold,
	BoldItalicFont = *-BoldItalic,
	Extension = .ttf
	]

luaotfload-tool -find DOES find the font where it's supposed to be. 

otfinfo -i shows me that the "description" field contains in its prose a few words contained in curly quotes.

If I edit the description field and remove these quotes using fontforge and install a newly generated font in place of the original everything works as it should: font found, document processed w/o any problems.

The original was downloaded from google fonts some time ago.

## Check/indicate
- [?] Relevant for XeTeX (NOT TESTED)
- [x] Relevant for LuaTeX
- [x ] Issue tracker has been searched for similar issues? (BRIEFLY)
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

In case it's a fontspec issue and the current version of the 4 fonts at google have been changed I still have the originals.

thanks

**Comment by khaledhosny** [comment]
I don’t see how any font metadata would influence fontspec. Also fontspec does not find fonts, it sets a `\font` command with the requested fonts and it is up to the engine to find the fonts. It would help if you share how/where the fonts are installed and the log of the failing job.

luaotfload-tool -find seems to search the font by name in luaotfload’s font database, but you are asking fontspec to load the font by file name, which works differently.
