### ISSUE TITLE
URLs do not use OpenType features under LuaLaTeX

### ISSUE THREAD

**Issue by adunning** [latex3/fontspec#474]
## Description
When writing a URL that includes numbers, these will appear as lining figures regardless of which OpenType features are enabled. This is a very old bug, [previously filed under Luaotfload](https://github.com/lualatex/luaotfload/issues/204), but the issue was determined not to rest there and it appears to have dropped off the radar.

## Check/indicate
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?
- [X] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```tex
\documentclass{article}

\usepackage{unicode-math}
\setmainfont{TeX Gyre Pagella}[Numbers = {Lowercase, Proportional}]
\usepackage{url}
\urlstyle{same}

\begin{document}

  1234567890

  \url{http://example.com/1234567890}

\end{document}
```

<img width="385" alt="Screenshot 2022-08-29 at 19 44 06" src="https://user-images.githubusercontent.com/1084407/187274837-78f8e721-b67f-436e-b0b7-04be216c3764.png">

## Further details

There is a [workaround on StackExchange](https://tex.stackexchange.com/questions/264206/cant-get-oldstyle-figures-in-url-with-lualatex) ~~but it no longer works with newer versions of LuaLaTeX~~.

**Comment by u-fischer** [comment]
> There was a [workaround on StackExchange](https://tex.stackexchange.com/questions/264206/cant-get-oldstyle-figures-in-url-with-lualatex), but it no longer works with newer versions of LuaLaTeX.

Sverre's answer works fine for me (but you have to change  the font name, Libertine Serif imho no longer works.)

**Comment by adunning** [comment]
> Sverre's answer works fine for me

Quite right, thank you – I've found the problem there, at least!

**Comment by khaledhosny** [comment]
I don’t see a fontspec issue here, it seems to be bad interaction between url package (that uses math mode) and luaotfload’s node mode (that does not work in math mode).

**Comment by adunning** [comment]
Where then would one file a report on this? In spite of it providing core functionality, `url` appears to be unmaintained.
