### ISSUE TITLE
Ligature or contextual-alternate bug in NewCM10-BoldItalic.otf: ft rendered as ſb

### ISSUE THREAD

**Issue by piater** [latex3/fontspec#475]
## Description
With default fonts, lualatex and xelatex render bold-italic `ft` as bold-italic `ſb`, where the first letter is a LATIN SMALL LETTER LONG S (U+017f).

## Check/indicate
- [X] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```
\documentclass{article}

% from \usepackage{fontsetup}:
\usepackage{fontspec}
% from \RequirePackage{fspdefault} inside fontsetup.sty:
\setmainfont[%
  BoldItalicFont=NewCM10-BoldItalic.otf,%
]{NewCM10-Book.otf}

\begin{document}
\textbf{\textit{ft}}            % bug

\textbf{\textit{ſ ſb b}}        % comparison
\end{document}
```

The resulting PDF shows a bold-italic rendering of
```
ſb
ſ ſb b
```
where the two `ſb` look exactly the same. Their constituents look slightly different than their isolated counterparts and are thus either contextual alternates (pdftotext gives me exactly these as individual characters, and Okular allows me to select the letters individually and copies them as `sb`) or ligatures (not sure how to tell).

## Further details

The error also occurs if the entire preamble above is replaced by `\usepackage{fontsetup}`, but I narrowed it down as above.

Removing the `\setmainfont` specification results in the use of LMRoman instead of NewCM, and the output looks correct but all characters are represented by their regular glyphs, irrespective of context.

Removing either or both of the `\text..{}` commands results in correct output (if the `\setmainfont` specification is completed accordingly), as does inserting a space between `f` and `t`. Interestingly, `f\-t` produces the same wrong result.

**Comment by u-fischer** [comment]
This is not related to fontspec

~~~~
\documentclass{article}

\begin{document}
\font\test="[NewCM10-BoldItalic.otf]:mode=node;script=latn;language=dflt;+tlig;+smcp;"
\test f ft ſ ſb b
\end{document}

~~~~

output with lualatex

![image](https://user-images.githubusercontent.com/4047173/189157287-4635a25b-d96a-4a0d-a0ca-102749273708.png)

output with xelatex

![image](https://user-images.githubusercontent.com/4047173/189157541-4da1efdc-809f-4c83-b280-7fa7edf72593.png)

Report this to the font maintainer.

**Comment by piater** [comment]
Thanks, Ulrike! The font maintainer has now fixed it upstream.
