### ISSUE TITLE
OSF in the SmallCaps font file

### ISSUE THREAD

**Issue by Mariusz-W** [latex3/fontspec#479]
I don’t see how _fontspec_ handles a situation, common with older OpenType font families, when the Roman OldStyleFigures reside in the SmallCaps font file. I don’t find a word about it in the current _fontspec_ documentation.

Something along the lines of :

SmallCapsFont = ⟨font name⟩  or  SwashFont = ⟨font name⟩

would be welcome.

The issue is important for me as there are many such font families available, some very refined.

**Comment by Mariusz-W** [comment]
I prepared a [tutorial](https://math.berkeley.edu/~wodzicki/X%E2%88%83TEX_fontspec_OsF%20figures%20in%20separate%20font%20files.html) in which I provide a temporary solution to the problem that a user of X∃LATEX and fontspec is facing when the desired set of glyphs for digits are located in external expert or SmallCaps font files.

**Comment by wspr** [comment]
Unfortunately this is not possible unless you use luaotfload to create custom virtual fonts. There isn't a standard or convenient mechanism in XeTeX or LuaTeX to switch fonts for certain characters for fontspec to provide an interface to.
