### ISSUE TITLE
explicit extension does not work in .fontspec files

### ISSUE THREAD

**Issue by kberry** [latex3/fontspec#480]
According to the "By file name" section in the documentation, and historical practice since the invention of .fontspec files, giving explicit extensions on font variants is supposed to be equivalent to giving the Extension variable. For example, these should be the same:
```
\defaultfontfeatures[MyCharis]
  {
    UprightFont = CharisSIL-Regular.ttf,
  }
```
\defaultfontfeatures[MyCharis]
  {
    Extension = .ttf,
    UprightFont = CharisSIL-Regular,
  }
```

Unfortunately, the former, with the explicit .ttf on UprightFont, no longer works. Minimal input file:
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{MyCharis}
\begin{document}
Hi.
\end{document}
```

gets error message:
```
! Package fontspec Error: The font "CharisSIL-Regular.ttf" cannot be found.
```

Whereas the second .fontspec, with "Extension = .ttf", works.

Hope it can be fixed. Thanks.

**Comment by niruvt** [comment]
This still is persistent. See: https://tex.stackexchange.com/q/675081

I hope it gets some attention from the developers.

**Comment by wspr** [comment]
Many apologies this has lingered so long. It should now be fixed for the next release of the package.

**Comment by kberry** [comment]
Thanks Will!
