### ISSUE TITLE
giving [options] before and/or after {fontname} with \setmainfont, etc.

### ISSUE THREAD

**Issue by kberry** [latex3/fontspec#481]
With fontspec, is there a difference, in general, betweeen
```
\setmainfont[option1,option2]{somefont}
```
and
```
\setmainfont{somefont}[option1,option2]
```
or even
```
\setmainfont{somefont}[option1,option2]
```
?

In the current documentation, I could only find mention of [options] after the {fontname}. But I have lots of documents where the [options] are given before, which (I'm guessing) I copied from previous iterations of the documentation and samples.

If the options can be given either way, it would be nice if the documentation could say so. If the options have to be given after to be reliable, it would be nice to say that. One way or the other ... --thanks, karl.

**Comment by u-fischer** [comment]
The actual definition is 

~~~~
\NewDocumentCommand \setmainfont { O{} m O{} }
  {
    \__fontspec_main_setmainfont:nn {#1,#3} {#2}
    \ignorespaces
  }
~~~~

so both places works (and you can even use both).

This is documented in section 5 "Miscellaneous font selecting details":

> The optional argument — from v2.4 For the first decade of fontspec’s life, optional font
features were selected with a bracketed argument before the font name, as in ....

**Comment by kberry** [comment]
Thanks much, Ulrike. "The order of arguments has been reversed" is not really a correct statement, but I suppose it's not worth worrying about, since the rest is clear.
