### ISSUE TITLE
\mathit behaves different, it's right?

### ISSUE THREAD

**Issue by libinxu01** [latex3/fontspec#482]
## Description
It looks that the default space between \mathit v and colon is different, is that right?
![企业微信20230103-210127](https://user-images.githubusercontent.com/15907992/210362433-f379922a-74ca-4e53-a028-0393cbee34bd.png)

## Check/indicate
Relevant for XeTeX

## Minimal example
```
\documentclass{article}
\usepackage{fontspec}

\begin{document}
:$\overline {\mathit{v}}$: \par
:$\overline {\mathrm{v}}$: \par
:$\overline {\mathbf{v}}$: \par
:$\overline {\mathsf{v}}$: \par
:$\overline {\mathtt{v}}$: \par
\end{document}
```

**Comment by wspr** [comment]
This is likely font-dependent behaviour. I don't foresee being able to control this using fontspec.
