### ISSUE TITLE
Get access to the different layers of a glyph \char<No>

### ISSUE THREAD

**Issue by cis555** [latex3/fontspec#485]
![0](https://github.com/latex3/fontspec/assets/65753567/368630aa-9eb3-4e79-ab5b-94673110b0e2)

Sometimes a glyph is composed of different layers.
Random example:
![1](https://github.com/latex3/fontspec/assets/65753567/9d91a131-9c6e-4857-9f29-5ff771463cb4)

But a command of type `\char[layer=2]"1F0AE` is **not available** at the moment.
_Would it be possible to create an addition that allows access to the contents of the different layers?_
Then outputs of the following type could be possible:
![2](https://github.com/latex3/fontspec/assets/65753567/5f3ba7f3-2f7d-4dbb-9d14-cc3419606dd4)

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{<a font whose glyphs have several layers>}
 \char[<layer options>]"1F0AE
\end{document}
```

PS: I added `ExampleFontWithLayers.ttf`, where `\char0` contains the shown situation with layers. 
[ExampleFontWithLayers01.zip](https://github.com/cis555/fontspec/blob/develop/ExampleFontWithLayers01.zip)

**Comment by wspr** [comment]
Do you know how to access the layers with plain luaotfload interfaces? (I am guessing this is not possible in XeTeX)

**Comment by khaledhosny** [comment]
There is no such thing as glyph layers in TrueType/OpenType fonts. This font was created with FontForge and the layers are a proprietary FontForge extension meant to be used FontForge when re-editing the font. The `glyf` table has only one glyph and it is the layer 1 showed above.

**Comment by khaledhosny** [comment]
To create colored glyphs, you can use [`COLR`](https://learn.microsoft.com/en-us/typography/opentype/spec/colr) table (but it is not supported by FontForge).

**Comment by wspr** [comment]
Based on Khaled's comments I think we have to close this one, nothing that can be done within fontspec sorry.
