### ISSUE TITLE
font shape undefined

### ISSUE THREAD

**Issue by githubgnulinux** [latex3/fontspec#487]
/tex/latex/fontspec/fontspec.cfg)))

"
LaTeX Font Warning: Font shape `TU//home/r' undefined
(Font)              using `TU/lmr/m/n' instead on input line 11.

! Illegal unit of measure (pt inserted).
<to be read again> 
                   t
l.11 ^^I]
"         

Configuration file:

"

%%% FONTSPEC.CFG %%%
%
% This configuration file sets up TeX Ligatures by default for all fonts loaded
% with `\setmainfont` and `\setsansfont`.
%
% In addition, `\setmonofont` has default features to enforce "monospace"
% settings with regard to space stretchability and shrinkability.
%
line 11: % Make a copy of this file in your own home TEXMF directory to set up your own
% defaults.

\defaultfontfeatures
 [\rmfamily,\sffamily]
 {Ligatures=TeX}

\defaultfontfeatures
 [\ttfamily]
 {WordSpace={1,0,0},
  HyphenChar=None,
  PunctuationSpace=WordSpace}

"

Advice of changes to make please?

**Comment by davidcarlisle** [comment]
This is a bug reporting form, if you believe you have found a bug please provide a test file to reproduce the issue. For general help queries, sites such as https://chat.stackexchange.com are more suitable, but you would still need to provide an example there.
