### ISSUE TITLE
[Question] Font Type 1 and `\setsansfont`

### ISSUE THREAD

**Issue by miticollo** [latex3/fontspec#489]
## Description
I'm preparing a presentation with beamer and I would want to use [`lxfonts`](https://ctan.org/pkg/lxfonts). At the moment in my preamble I added DejaVu fonts:
```latex
\setsansfont{DejaVuLGCSans}[
	Path		= fonts/dejavu/sans/ ,
	Extension	= .ttf ,
	BoldFont        = *-Bold ,
	ItalicFont      = *-Oblique ,
	BoldItalicFont	= *-BoldOblique ,
	UprightFont	= * ,
]
```
EVERYTHING WORKS AS EXPECTED!

**But is it possible use `\setsansfont`, like above, with a Type 1 font?**
I discovered that the `UprightFont` is called [leclq8.pfb](http://mirrors.ctan.org/fonts/lxfonts/fonts/type1/leclq8.pfb) so I tried
```latex
\setsansfont{leclq8}[
	Path		= fonts/dejavu/sans/ ,
	Extension	= .pfb ,
	UprightFont	= * ,
]
```
BUT IT DOESN'T WORK!
(compiled with `latexmk -interaction=nonstopmode -synctex=1 -lualatex ./foo.tex`)

Then I read the documentation of `luaotfload` and I found at page [11](https://ctan.mirror.garr.it/mirrors/ctan/macros/luatex/generic/luaotfload/luaotfload-latex.pdf#page=11)
![screenshot](https://github.com/latex3/fontspec/assets/30465144/e0913be7-6cab-44ce-9729-b2c52b334dfa)
So I'm a bit confused because I don't understand if it is possible use a Type 1 font, like above.

**Comment by davidcarlisle** [comment]
Please note this is a bug report form, not a support forum, stackexchange or similar would be more suitable for general questions.

To give a reasonable interface to T1 encoded fonts you neeed to disable most of the Unicode handling, just loading the font does not do anything reasonable, even if it does not give errors.

For example the `ec-lmr10` example you give produces

![image](https://github.com/latex3/fontspec/assets/1268738/da283e44-1e5b-440c-8db2-2cca2202b502)



from 

```
\documentclass{article}
\begin{document}
\font\lmromanten = {file:ec-lmr10} at 10pt \lmromanten

«Gruß»

\end{document}
```
