### ISSUE TITLE
OpenType c2sc feature works improperly

### ISSUE THREAD

**Issue by YellowJacketLinux** [latex3/fontspec#497]
## Description

The c2sc OpenType feature is supposed to use the small-caps variant of the lower case letter where the upper case letter is requested, but the unicode code-point should still be for the upper-case variant so that copy and paste still produces an upper-case letter regardless of font features in the document being pasted into.

## Check/indicate
- [ ?] Relevant for XeTeX
- [ YES] Relevant for LuaTeX
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\RequirePackage{fontspec}
\documentclass[letterpaper,fontsize=14pt]{scrarticle}

\setmainfont
  [ Ligatures   = TeX ,
    Extension   = .otf ,
    UprightFont = *-regular ,
    BoldFont = *-bold ,
    ItalicFont = *-italic ,
    BoldItalicFont = *-bolditalic ]
  {texgyretermes}
\setsansfont
  [ Ligatures   = TeX ,
    Extension   = .otf ,
    UprightFont = *-regular ,
    BoldFont = *-bold ,
    ItalicFont = *-italic ,
    BoldItalicFont = *-bolditalic ]
  {texgyreheros}
\setmonofont
  [ Ligatures   = NoCommon ,
    Extension   = .otf ,
    UprightFont = *-regular ,
    BoldFont = *-bold ,
    ItalicFont = *-italic ,
    BoldItalicFont = *-bolditalic ]
  {texgyrecursor}

\usepackage[colorlinks=true]{hyperref}

\begin{document}
\section{Stuff}
Herod the Great died at around
4~{\fontspec[Letters=UppercaseSmallCaps]{texgyretermes-regular.otf}B.C.E.}\
but Quirinius did not become governor of Syria until
6~{\fontspec[Letters=UppercaseSmallCaps]{texgyretermes-regular.otf}C.E.}\
which means the tax of Quirinius did not happen until at least ten years after Herod the Great died.

\end{document}
```

## Further details

With the above example, the resulting PDF (when compiled with `lualatex` renders correctly however copy the string and paste it elsewhere, and both the `B.C.E.` and `C.E.` will be lower-case, indicating that the lower-case unicode code points were used.

**Comment by wspr** [comment]
Sorry, this is an engine issue which fontspec doesn't have any ability to change. Not saying the behaviour you're seeing is right or wrong, just that the package can't do anything about it.
