### ISSUE TITLE
Undefined control sequence. \begin{document}

### ISSUE THREAD

**Issue by ryder1977** [latex3/fontspec#503]
## Description

After Update to 2.9a this happened. I have no idea what it means :)

3849: Undefined control sequence. \bool_if:NT \g__fontspec_cfg_bool
3849: Missing number, treated as zero. \bool_if:NT \g__fontspec_cfg_bool
30: Undefined control sequence. \begin{document}
30: Missing number, treated as zero. \begin{document}

## Check/indicate
- [ ] Relevant for XeTeX
- [x ] Relevant for LuaTeX
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
% !TEX TS-program = lualatex
% !TEX encoding = UTF-8 Unicode
% !TEX spellcheck = de-DE

\documentclass[fontsize=12pt, paper=a4,headings=small,%
openany, toc=chapterentrydotfill,numbers=enddot]{scrbook}
\usepackage[utf8]{luainputenc}


\usepackage{aurical}	
\usepackage{pigpen}	


\usepackage[ngerman]{babel}	
\usepackage{lipsum}


\usepackage{fontspec-luatex}
\setkomafont{descriptionlabel}{\normalfont\bfseries }
\usepackage{enumitem}

\pagestyle{plain}
\usepackage{graphicx}
\usepackage{pdfpages}
\usepackage[pass]{geometry}



\begin{document}
	
	\mainmatter	
	\lipsum[1-2]

\end{document}
```

## Further details
Happened after update to 2.9a
fontspec-luatex.sty    2024/02/13 v2.9a Font selection for XeLaTeX and LuaLaTeX

**Comment by davidcarlisle** [comment]
A minimal example would be

```
\documentclass{article}


\usepackage{fontspec-luatex}

\begin{document}

\end{document}
```

**Comment by ryder1977** [comment]
Ah thanks for your explanation :)
I added all my used packages because I thought there may be some interference.
Thank you for your time.
Bernd

**Comment by davidcarlisle** [comment]
incidentally aree you sure you want to use `luainputenc` it has some specialist uses but it breaks most luatex Uniocde support.

**Comment by ryder1977** [comment]
Didnt know that. So you recommend not using it?

**Comment by davidcarlisle** [comment]
As I say it has very specialist uses mostly around using legacy 8 bit fonts with luatex but if you are doing that you know you are doing that, it disables luatex's Unicode handling and replaces it by essentially the inputenc handling as used in pdftex, but using a Unicode tex and disabling its unicode support isn't something you want to do routinely.

**Comment by ryder1977** [comment]
Great, thanks for your advice an time.
