### ISSUE TITLE
With `fontspec` 2.9b, a font is wrongly claimed to be not found

### ISSUE THREAD

**Issue by dbitouze** [latex3/fontspec#510]
## Description
With `fontspec` 2.9b, a font is wrongly claimed to be not found.

## Check/indicate
- [x] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{FiraCode-Regular.ttf}[ItalicFont= FiraCode-RegularItalic.otf]
\begin{document}
Foo
\end{document}
```

## Further details

With `fontspec`:

- v2.9a, the previous MCE used to:
    - `lualatex`-compile,
    -  not `xelatex`-compile: that failed with the error:
    > ! Package fontspec Error: The font "FiraCode-Regular" cannot be found.
    > 
    > For immediate help type H <return>.
    >  ...                                              
    >                                                   
    > l.3 ...}[ItalicFont= FiraCode-RegularItalic.otf]
    >                                                   
    > ? 

- v2.9b, the previous MCE fails to both `lualatex`-compile and `xelatex`-compile, with the error (the first line only with `lualatex`):
    > luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: File not found: "FiraCode-Regular.otf".
    > 
    > ! Package fontspec Error: 
    > (fontspec)                The font "FiraCode-Regular" cannot be found; this
    > (fontspec)                may be but usually is not a fontspec bug. Either
    > (fontspec)                there is a typo in the font name/file, the font is
    > (fontspec)                not installed (correctly), or there is a bug in
    > (fontspec)                the underlying font loading engine
    > (fontspec)                (XeTeX/luaotfload).
    > 
    > For immediate help type H <return>.
    >  ...                                              
    >                                                   
    > l.3 ....ttf}[ItalicFont= FiraCode-RegularItalic.otf]
    >                                                   
    > ?

BTW, with `fontspec` 2.9b, the following MCE:

```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{FiraCode-Regular.ttf}
\begin{document}
Foo
\end{document}
```
- `lualatex`-compiles,
-  not `xelatex`-compiles: that failed with the error:
  > ! Package fontspec Error: The font "FiraCode-Regular" cannot be found.
  > 
  > For immediate help type H <return>.
  >  ...                                              
  >                                                   
  > l.3 ...}[ItalicFont= FiraCode-RegularItalic.otf]
  >                                                   
  > ?

**Comment by u-fischer** [comment]
Where did you get the fonts? There is no FiraCode-Regular.ttf in texlive, and at https://github.com/tonsky/FiraCode I only find ttf-files and  no `FiraCode-RegularItalic.otf`

After I installed the firacode fonts (in my system), `\setmonofont{FiraCode-Regular.ttf}` worked fine for me with lualatex and xelatex.

**Comment by dbitouze** [comment]
> Where did you get the fonts? There is no FiraCode-Regular.ttf in texlive, and at https://github.com/tonsky/FiraCode I only find ttf-files and no `FiraCode-RegularItalic.otf`

A friend gave them to me. But I guess they come from [this repository](https://github.com/Avi-D-coder/FiraCode-italic).

> After I installed the firacode fonts (in my system), `\setmonofont{FiraCode-Regular.ttf}` worked fine for me with lualatex and xelatex.

Strange! My system is GNU/Linux Mageia 9 with a vanilla install of TeX Live 2024. And:

```
$ fc-list | grep FiraCode-Regular
/usr/share/fonts/drakfont/Type1/FiraCode-Regular.pfb: Fira Code:style=Regular
/usr/share/fonts/drakfont/ttf/FiraCode-Regular.ttf: Fira Code:style=Regular
/usr/share/fonts/drakfont/otf/FiraCode-RegularItalic.otf: Fira Code:style=Regular Italic,Italic
```

**Comment by wspr** [comment]
I thought this might be a bug with mixing ttf and otf extensions in the same font family call, but this seems to work for me:
```
\documentclass{article}
\usepackage{fontspec}
\setmonofont{Ysabeau-Regular.otf}[ItalicFont=Lato-Regular.ttf]
\begin{document}
\ttfamily
Foo
\itshape
Foo
\end{document}
```
At the moment I am thinking this might not be a fontspec issue, so I'll close this issue now to avoid it lingering -- but let me know if you can find another example.

**Comment by dbitouze** [comment]
> At the moment I am thinking this might not be a fontspec issue, so I'll close this issue now to avoid it lingering -- but let me know if you can find another example.

But isn't it a bug of `fontspec` that the following MCE doesn't compile with `xelatex`?
```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{FiraCode-Regular.ttf}
\begin{document}
Foo
\end{document}
```

**Comment by u-fischer** [comment]
> But isn't it a bug of `fontspec` that the following MCE doesn't compile with `xelatex`?

It compiles fine for me. But you can test if it is a problem with fontspec or your font installation by compiling without fontspec:

~~~~
\documentclass{article}
\begin{document}
\font\test="[FiraCode-Regular.ttf]/OT:script=latn;language=dflt;" \test blub
\end{document}
~~~~

**Comment by wspr** [comment]
@dbitouze  — I don't understand this example. The `*` notation is intended to copy the first argument into the subsequent arguments, and the `Extension` notation is to add `.otf` to them. So it seems correct that fontspec would be looking for:

* TeX Gyre Pagella-Regular.otf
* TeX Gyre Pagella-Bold.otf
* TeX Gyre Pagella-Italic.otf
* TeX Gyre Pagella-BoldItalic.otf

And it also seems correct that it couldn't find these fonts using those filenames. How this ever worked I'm not too sure, but it was surely a mis-feature.

**Comment by dbitouze** [comment]
@wspr OK, thanks: removing the `Extension = .otf` option makes it work. Nevertheless, another example which used to work and that doesn't work anymore:
```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{GoMono}[
UprightFont    = *-Regular,
BoldFont       = *-Bold,
ItalicFont     = *-Regular-Italic,
BoldItalicFont = *-Bold-Italic,
]
\begin{document}
\ttfamily
Test
\textbf{Test}
\textit{Test}
\textbf{\textit{Test}}
\end{document}
```
despite:
```
$ fc-list | rg GoMono | rg tf
/usr/local/texlive/2024/texmf-dist/fonts/truetype/bh/gofonts/GoMono-Regular.ttf: Go Mono:style=Regular
/usr/local/texlive/2024/texmf-dist/fonts/truetype/bh/gofonts/GoMono-Bold-Italic.ttf: Go Mono:style=Bold Italic
/usr/local/texlive/2024/texmf-dist/fonts/truetype/bh/gofonts/GoMono-Regular-Italic.ttf: Go Mono:style=Italic
/usr/local/texlive/2024/texmf-dist/fonts/truetype/bh/gofonts/GoMono-Bold.ttf: Go Mono:style=Bold
```
OK, the expected result is obtained with just `\setmonofont{GoMono}` (without the options specifying the UprightFont, BoldFont, ItalicFont, and BoldItalicFont).

**Comment by dbitouze** [comment]
> hmmm, this seems to be working for me in LuaTeX right now (albeit with a prerelease fontspec). But I think it's dangerous to ask for a file on disk without also giving an extension or specifying "Path" — otherwise you are relying on heuristics of the engine searching for the font name, failing to find it, then falling back to searching on disk.

@wspr OK but still it was working before :wink:

But I'm a bit lost: could you please give the code that should be used for this GoMono font with the extension provided and the UprightFont, BoldFont, ItalicFont, BoldItalicFont specified?

**Comment by wspr** [comment]
@dbitouze  — apologies for the inconvenience here! I am sorry that these changes have caused issues.

I prefer to load fonts by filename to avoid portability issues so I would recommend here:

```
\setmonofont{GoMono}[
Extension = .ttf,
UprightFont    = *-Regular,
BoldFont       = *-Bold,
ItalicFont     = *-Regular-Italic,
BoldItalicFont = *-Bold-Italic,
]
```

**Comment by dbitouze** [comment]
@wspr You're welcome! Many thanks to you for your answer, for `fontspec` and for your numerous other contributions!

**Comment by dbitouze** [comment]
For what it's worth, with `fontspec` v2.9d, the file of the OP:
```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{FiraCode-Regular.ttf}[ItalicFont= FiraCode-RegularItalic.otf]
\begin{document}
Foo
\end{document}
```
- now compiles with `lualatex`,
- still doesn't compile with `xelatex`, with the same error:
```
! Package fontspec Error: 
(fontspec)                The font "FiraCode-Regular" cannot be found; this
(fontspec)                may be but usually is not a fontspec bug. Either
(fontspec)                there is a typo in the font name/file, the font is
(fontspec)                not installed (correctly), or there is a bug in
(fontspec)                the underlying font loading engine
(fontspec)                (XeTeX/luaotfload).

For immediate help type H <return>.
 ...                                              
                                                  
l.3 ...tf}[ItalicFont= FiraCode-RegularItalic.otf]
                                                  
?
```

**Comment by wspr** [comment]
@dbitouze — thanks for letting me know... this was definitely supposed to be fixed! :(

**Comment by khaledhosny** [comment]
XeTeX does not load system fonts by file name, only TDS fonts, and vice versa. Luaotfload will load system fonts by file names (unless `kpse:` prefix is used).

**Comment by dbitouze** [comment]
> XeTeX does not load system fonts by file name, only TDS fonts, and vice versa. Luaotfload will load system fonts by file names (unless `kpse:` prefix is used).

@khaledhosny Thanks! But, given that:
```
$ fc-list | rg -v wght | rg -v pfb | rg FiraCode | rg Italic
/usr/share/fonts/drakfont/otf/FiraCode-BoldItalic.otf: Fira Code:style=Bold Italic
/usr/share/fonts/drakfont/otf/FiraCode-RegularItalic.otf: Fira Code:style=Regular Italic,Italic
```
what would be with XeTeX the code to use in order to get the font provided by `FiraCode-RegularItalic.otf` (last line above) as `ItalicFont`?

**Comment by khaledhosny** [comment]
`\setmonofont{Fira Code}` should work, you don’t need to explicitly specify `ItalicFont`.

Bit if you want to load the fonts by file name, then the simplest solution is to copy them to the current directory.

**Comment by wspr** [comment]
Shouldn't it also work to write `Path=/usr/share/fonts/drakfont/otf/` ?

**Comment by khaledhosny** [comment]
That would work too.
