### ISSUE TITLE
New release of fontspec breaks \babelfont in xelatex

### ISSUE THREAD

**Issue by borisveytsman** [latex3/fontspec#513]
## Description
The new release (71101 in TeXLive) breaks \babelfont command in xelatex, but not lualtex

## Check/indicate
- [x] Relevant for XeTeX
- [ ] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [x] Links https://tug.org/pipermail/tex-live/2024-April/050481.html

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage[english]{babel}
\babelfont[chinese]{rm}[
  Extension=.otf,
  UprightFont=*-Regular,
  BoldFont=*-Bold
]{FandolHei}
\begin{document}
\foreignlanguage{chinese}{你好世界}
\end{document}

```

## Further details
This document fails the recent xelatex with the message
```
) (/usr/local/texlive/2024/texmf-dist/tex/latex/base/ts1cmr.fd)
! Illegal parameter number in definition of \l__exp_internal_tl.
<to be read again> 
                   1
l.9 \foreignlanguage{chinese}{你好世界}
```
It compiles in lualatex.  It also compiles in xelatex and the previous version of fontspec (after `sudo tlmgr restore fontspec 69833`)

**Comment by jpcirrus** [comment]
Just to add that the new fontspec 2.9b release is preventing document compilation here using lualatex (does with xelatex) when the document changes language from the default of en-NZ. Let me know if you want me to raise a separate issue.

Error message:

```
 Illegal parameter number in definition of \l__exp_internal_tl.
<to be read again> 
1
l.561 \begin{otherlanguage}{arabic}
```

**Comment by wspr** [comment]
@jpcirrus — thanks John, a separate issue isn't required I think but could you provide a minimal example of what is failing for you? (Similar to Boris's example above)

**Comment by jpcirrus** [comment]
In reducing the complex document where I experienced the compilation error to a MWE, I found that both xelatex and lualatex are affected. This issue is that for every font-family declared with `\babelfont` for the main language, the corresponding `\babelfont[language-list]` font-family has also to be declared, even if never used, which prior to `fontspec` 2.9b was not the case.

```latex
\documentclass{article}
\usepackage[english]{babel}
\babelfont{rm}{Latin Modern Roman}
\babelfont{sf}{Latin Modern Sans}
% \babelfont{tt}{Latin Modern Mono}
\babelfont[arabic]{rm}{FreeSerif}
% \babelfont[arabic]{sf}{FreeSerif}
% \babelfont[arabic]{tt}{FreeSerif}
\begin{document}
\foreignlanguage{arabic}{آليات}
\end{document}
```

The reason I had previously thought it was lualatex only was that I was using the command `\babelprovide[onchar=fonts ids]{arabic}` without actually marking up the language changes, which compiled with xelatex, but on more rigorous inspection wasn't using the specified font.

**Comment by u-fischer** [comment]
and an example without babel is

~~~~
\documentclass{article}
\usepackage{fontspec}
\begin{document}
\fontspec[Script=Cyrillic,Language=Russian]{opensans}

\end{document}
~~~~

**Comment by u-fischer** [comment]
If I change the code to this it compiles again (but I'm not completely sure that the logic is right (and why script stores both the name and the internal tag and the lang doesn't).

~~~~
\cs_new:Nn \fontspec_new_lang:nn
  {
    \keys_define:nn {fontspec-opentype} { Language / #1 .code:n =
      {
        \bool_set_false:N \l__fontspec_scriptlang_exist_bool
        \clist_map_inline:nn {#2}
          {
            \exp_args:No \__fontspec_check_lang:NnTF \l__fontspec_fontface_cs_tl {####1}
              {
                \tl_set:Nn \l__fontspec_lang_tl {####1}
                \int_set:Nn \l__fontspec_language_int {\l__fontspec_strnum_int}
                \tl_gset:Nx \g__fontspec_single_feat_tl { language=####1 }
                \bool_set_true:N \l__fontspec_scriptlang_exist_bool
                \clist_map_break:
              }
          }
% exchange this part so that is handles lang not script.
        \bool_if:NF \l__fontspec_scriptlang_exist_bool
          {
            \__fontspec_warning:nx {language-not-exist} {#1}
            \clist_set:Nn \l_tmpa_clist {#2}
            \clist_get:NN \l_tmpa_clist \l__fontspec_lang_tl
            \exp_args:Noo \__fontspec_check_lang:NnTF \l__fontspec_fontface_cs_tl 
            \l__fontspec_lang_tl
              {} % F variant of conditional missing, must be added 
              {
                \int_set:Nn \l__fontspec_language_int {\l__fontspec_strnum_int}                
                \tl_gset:Nx \g__fontspec_single_feat_tl { language=\l__fontspec_lang_tl }               
              }
          }
      }
    }
  }
~~~~

**Comment by nplatis** [comment]
If it is of any importance, a document similar to the one of @borisveytsman produces the error only for _some_ fonts on my system; for example, Arial gives an error, whereas Calibri does not.

**Comment by u-fischer** [comment]
@wspr there should be imho an update soon, various people have already commented about the issue e.g. on the texlive list.

**Comment by wspr** [comment]
> @wspr there should be imho an update soon, various people have already commented about the issue e.g. on the texlive list.

I agree -- can anyone confirm if the current develop branch now fixes all the issues, or do Nikos/John's examples above show different problems?

**Comment by u-fischer** [comment]
@wspr I checked all the examples and see no problems.
