### ISSUE TITLE
WordSpace under LuaLaTeX seems funny

### ISSUE THREAD

**Issue by wspr** [latex3/fontspec#56]
E.g.,

<pre>
\documentclass[twocolumn]{article}
\usepackage{fontspec}
\begin{document}
\parbox{8cm}{
   \fontspec{TeX Gyre Termes}
   Some text for our example to take up some
   space, and to demonstrate the default interword space.
   \bigskip

   \addfontfeature{ WordSpace = 0.2 }
   Some text for our example to take up some
   space, and to demonstrate the default interword space.
}
\end{document}
</pre>

**Comment by u-fischer** [comment]
This is no longer relevant. As documentated `WordSpace` can't be used in `\addfontfeatures` (and it errors).
