### ISSUE TITLE
xdvipdfmx produces a warning in beamer shadow outer theme.

### ISSUE THREAD

**Issue by leo-liu** [latex3/fontspec#95]
This is the minimal (as I can) code:

``` latex
\documentclass{beamer}% v3.10
\useoutertheme{shadow}
\usepackage{fontspec}% v2.1e
\begin{document}
\section{foo}
\frame{\null}
\end{document}
```

I compile it with

```
xelatex -no-pdf test.tex
xdvipdfmx test.xdv
```

 and get these warnings (from `xdvipdfmx`):

```
** WARNING ** Annotation out of page boundary.
** WARNING ** Current page's MediaBox: [0 0 362.835 272.126]
** WARNING ** Annotation: [164.443 264.278 172.913 273.053]
** WARNING ** Maybe incorrect paper size specified.
```

The warnings will be gone without `fontspec`.

I'm not sure whether it is a `fontspec` issue. It seems that the bug (if it is) doesn't ruin anything, but I still want to know why. Thanks.

**Comment by u-fischer** [comment]
Closing as there is no warning with a current texlive (and it is not a fontspec problem either).
